Tell me who your friends are and I'll tell you who you are.=Arkadaşını söyle, kim olduğunu söyleyeyim.
I'll tell the world about it.=Bunu herkese söyleyeceğim.
I'm telling you once and for all.=Size son olarak söylüyorum.
I told you so.=Ben size söylemiştim.
Tell them to be ready at two.=Onlara söyle, saat ikide hazır olsunlar.
Please tell her that.=Lütfen bunu ona söyleyiniz.
I don't know what to tell you.=Size ne söyleyeceğimi bilemiyorum.
What if we don't tell them anything?=Onlara hiçbir şey söylemesek?
I won't say another word!=Başka bir şey söylemem!
I said that but not in that sense.=Ben bunu söyledim, ancak o anlamda değil.
He can't have said that.=Bunu söylemiş olamaz.
It would be better if you didn't say anything.=Hiçbir şey söylemesen, daha iyi olur.
I wish I had never said that.=Söylemez olaydım.
I've said to them I wasn't to be disturbed during the meeting.=Toplantı esnasında beni aramamalarını söylemiştim.
Have you anything to say about it?=Bu konuda söyleyeceklerin var mı?
Let's hear what he has to say.=Söyleyeceklerini dinleyelim bakalım.
Think before you speak.=Önce düşün, sonra söyle.
If I have said so, what of it?=Söylemişsem, ne çıkar?
What could one say?=Ne söyleyebilirim ki?
Never mind what I say!=Ne söylersem söylerim!
Now that you mention it, I remember.=Sen söyleyince hatırladım.
Just speak your mind=Ne düşündüğünü açıkça söyle.
If only it could talk.=Dili olsa da söylese!
Ask her to come in.=içeri gelmesini söyle.
Do you realize what you're saying?=Siz neler söylüyorsunuz!
If he is to be believed no one approved of the plan.=Söylediklerine bakılırsa, kimse planı beğenmemiş.
Say what you will, it won't change a thing.=Sen ne söylersen söyle, hiçbir şey değişmez.
Let me tell you that much.=Şu kadarını söyleyeyim.
Spare your words and spare the trouble.=Az söyleyen, rahat eder.
Shall I tell you something?=Ben size bir şey söyleyeyim mi?
One must think well first, then speak.=Bir şeyi iyice düşünmeli, sonra söylemeli.
You pretend you've never said such a thing and I'll pretend not to have heard it.=Sen bunu söylememiş ol, ben de işitmemiş olayım.
Ask no questions and you'll be told no lies.=Ne sen sor, ne de ben söyleyeyim.
Well, I've warned you!=Benden söylemesi!
If you excuse the expression=Ayıptır söylemesi.
I can say this much for the moment.=Şimdilik bu kadarını söyleyebilirim.
Listen a lot but speak a little.=İki dinle, bir söyle.
Speak briefly but to the point.=Az söyle, öz söyle.
Listen well first, speak later.=Bin işit, bir söyle.
While boasting of one's deeds one reveals one's defects=Şecaat arz ederken, merd-i kıpti sirkatin söyler.
Do not pass as true what you have heard.=Yalancı, işittiğini söyleyendir.
Speak what you like and you'll hear what you don't.=İstediğini söyleyen, istemediğini işitir.
to try to get a message across indirectly.=Kızım sana söylüyorum, gelinim sen anla.
Don't disclose your secret to a friend, he'll tell it to his friend.=Açma sırrını dostuna, o da söyler dostuna.
A friend will tell the bitter truth.=Dost acı söyler.
They are making no secret of it.=Onlar bunu açık açık söylüyorlar.
I told them whatever came to my mind.=Onlara ağzıma geleni söyledim.
No one is saying the opposite.=Bunun aksini söyleyen yok ki!
I don't want to appear to talk behind him.=Arkasından söylemek gibi olmasın.
Eat big mouthfuls, don't talk big.=Büyük lokma ye, büyük söz söyleme.
If you're harsh with others, they'll get even with you.=Kötü söyleme eşine, ağu katar aşına.
Let me tell you in advance.=Size peşinen söyleyeyim.
Give them my best regards.=Onlara benden selam söyle.
Remind me to the children.=Çocuklara benden selâm söyle.
He sends you his best regards.=Size selâm söyledi.
They sang and danced all night long.=Bütün gece oynayıp şarkı söylediler.
Don't breathe a word about this matter.=Bu konu hakkında tek kelime söylemeyin.
He hinted that he would not be able to pay the bill.=Senedi ödeyemeyeceğini üstü kapalı bir şekilde bildirdi.
I won't lie to you.=Ne yalan söyleyeyim.
If you're lying, I shall know.=Yalan söylüyorsun, haberim olur.
It seems to me that they are lying.=Bana öyle geliyor ki, bunlar yalan söylüyor.
They are openly lying=Göz göre göre yalan söylüyorlar.
He is barefacedly lying.=Gözünün içine baka baka yalan söylüyor.
He never means what he says.=O hep yalandan söyler.
I shall tell him to his face what I think of him.=Onun hakkında ne düşündüğümü yüzüne söyleyeceğim.
How can one say such a thing in public?=Herkesin önünde öyle söylenilir mi?
It is said that he is very rich.=Çok zengin olduğu söyleniyor.
A great deal has been said on this matter.=Bu konu hakkında birçok şey söylendi.
That's not something one can say in public.=Bu, herkesin içinde söylenecek bir şey değil.
Apples are said to be very useful.=Elmanın çok faydalı olduğu söyleniyor.
There isn't much to be said for it.=Onun yararına pek çok şey söylenemez.
I was told so.=Bana öyle söylendi.
Were you not told to come quickly?=Sana çabuk gelmen söylenmedi mi?
What do you tell someone who doesn't listen?=Söz dinlemeyen birine ne söylenir ki?
Contrary to what has been rumoured, the government will not resign.=Söylenenlerin tersine, hükümet istifa etmeyecektir.
It is rumoured that he is still alive.=Hâlâ hayatta olduğu söyleniyor.
The people are already grumbling.=Halk söylenmeye başladı.
Once she starts grumbling, she won't stop.=O söylenmeye başladı mı, artık susmaz.
If you're not going to do it willingly, leave it.=Bu işi, öyle söylene söylene yapacaksan, bırak kalsın.
Why do they make these people lie?=Bu insanlara neden yalan söyletiyorlar?
No one can make me say such things.=Kimse bana böyle şeyleri söyletemez.
Don't make me talk!=Beni söyletme!
How will I make him tell these things?=Ben ona bunları nasıl söyleteceğim?
Look for the motive behind the action.=Söyleyene bakma, söyletene bak.
If you pay him five pence to talk, you'll pay him ten to shut up.=Beş para ver söylet, on para ver sustur.
Sometimes it's God that inspires what people say.=Söyleyene değil, söyletene bak.
Don't bring up that matter if you don't want to hear something unpleasant.=Açtırma kutuyu, söyletme kötüyü.
Wealth breeds wealth, poverty breeds grumbling.=Var varlatır, yok söyletir.
I was going to say a lot of things but they didn't let me.=Birçok şey söyleyecektim, söyletmediler.
In the declaration it was question of a commander=Bildiride bir komutandan söz ediliyordu.
Did you mention the delay to him?=Ona gecikmeden söz ettiniz mi?
I don't know what you're talking about.=Neden söz ettiğinizi bilmiyorum.
What are you talking about?=Sen neden söz ediyorsun?
The children are already talking about getting back.=Çocuklar daha şimdiden dönmekten söz ediyorlar.
Where is the equality you're talking about?=Siz hangi eşitlikten söz ediyorsunuz?
He keeps talking about the old successes of the team=Takımın eski başarılarından söz edip duruyor.
Don't tell anyone about this.=Bundan kimseye söz etmeyiniz.
None of the incidents he alludes to are real.=Söz ettiği olayların hiç biri gerçek değil.
to talk of indifferent things=havadan sudan söz etmek
to talk shop.=işten söz etmek
to talk about this and that.=şundan bundan söz etmek
For the sake of saying smth=Söz olsun diye.
I have no say in this matter=Bu konuda hiç söz hakkım yok.
It's a question of loss of jobs=Söz konusu iş kaybıdır.
Our future is at stake here=Burada geleceğimiz söz konusudur
Such a proposal is out of the question.=Böyle bir teklif söz konusu olamaz.
There is no question of sending him back.=Onun geri gönderilmesi söz konusu değil
There can be no question of forgiving them.=Onların af edilmeleri söz konusu olamaz.
It's out of the question.=Bu, söz konusu olamaz.
He thinks people will start talking.=Aklı sıra, söz olur
Would you believe it? He has no say in this.=İnanır mısınız? Bu işte söz sahibi değil.
It's not worth wasting one's breath on.=Bunun sözü mü olur?
I have a word or two to say to you.=Sana bir çift sözüm var.
A promise made is a promise kept.=İnsan, sözünün eri olmalıdır
He has always been a man of his word=O, daima sözünün eri olmuştur.
Where did you do your internship?=Stajınızı nerede yaptınız?
We have to stock up before the price increase.=Zam gelmeden stoklamalıyız.
The government warned the population again against stocking up sugar.=Hükümet halkı şeker stoklamaya karşı bir kere daha uyardı.
What is excusable for a superior is an offense for a subordinate=Hanım kırarsa kaza, halayık kırarsa suç.
It's your fault=Suç sende.
What is the police charging him with?=Polis onu ne ile suçluyor?
What are you accusing these innocent people of?=Bu masum insanları neyle suçluyorsunuz?
They are accusing each other of cheating.=Birbirlerini hile yapmakla suçluyorlar.
The press is blaming the government for creating an artificial crisis.=Basın, hükümeti suni bir kriz yaratmakla suçluyor.
You needn't blame anyone for that.=Bunun için kimseyi suçlamana gerek yok.
Please don't blame yourself in this manner.=Lütfen kendinizi böyle suç Utmayınız.
What are these students accused of?=Bu öğrenciler ne ile suçlanıyor?
What are we charged with doing?=Biz ne yapmakla suçlanıyoruz?
Might is right=Hem suçlu, hem güçlü
Everyone is presumed innocent until proved guilty.=Herkes, suçlu olduğu kanıtlanmadıkça suçsuz sayılır.
I don't want to abuse your generosity.=Sizin iyiliğinizi suistimal etmek istemiyorum.
Dilute with half a glass of water.=Yarım bardak suyla sulandırınız.
There is no need to water it down.=Onu sulandırmaya gerek yok.
These dishes make my mouth water.=Bu yemekler ağzımı sulandırıyor.
We offer our clients a wide variety of services.=Müşterilerimize çok çeşitli hizmetler sunuyoruz
We are offering you very favourable terms.=Size çok uygun şartlar sunuyoruz.
The chairman is going to present the doctor with the award=Başkan, doktora ödülü sunacak.
Who is going to present the programme?=Programı kim sunacak?
We'll submit our answer in writing to the committee.=Cevabımızı yazılı olarak komisyona sunacağız.
It's too late for submitting new proposals.=Yeni öneriler sunmak için çok geç.
My wife sends her kindest regards.=Eşim en iyi dileklerini sunar.
My wife and I send our deepest sympathy.=Eşim ve sen kederinizi içten paylaşır, taziyelerimizi sunarız.
The children join me in sending you our best wishes.=Çocuklar ve ben en iyi dileklerimizi sunarız.
I wish you the best of luck=Size bol şans sunarım.
Heartfelt condolences in your great loss=Büyük kaybınız dolayısıyla içten taziyelerimi sunarım.
All my best wishes.=En iyi dileklerimi sunarım.
Yours sincerely.=Saygılarımızı sunarız.
One day we must go and pay our respects to the new governor.=Bir gün yeni valiyi ziyaret edip saygılarımızı sunmamız gerek.
We shall bring the matter to the Minister's attention.=Konuyu bakanın dikkatine sunacağız.
A new detergent is now on sale at markets.=Marketlerde yeni bir deterjan satışa sunuldu
The hungry will not have enough to eat, the thirsty not enough to drink.=Acıkan doymam; susayan, kanmam sanır.
We, the fans, are thirsty for success in Europe.=Biz taraftarlar, Avrupa'da başarıya susamışız.
They are all out for blood.=Bunların hepsi kana susamış.
I've decided to remain silent in this regard.=Bu konuda konuşmamaya karar verdim.
Once that man starts talking, he won't stop.=Bu adam konuşmaya başladı mı, artık susmaz.
Please be quiet!=Lütfen susunuz!
He made a sign as if to say keep silent.="Sus" der gibi bir işaret etti.
I just bit my lips and kept quiet.=Dişimi sıkıp sustum.
Can't you make these children keep quiet?=Şu çocukları susturamaz mısınız?
He tried to say something but the chairman shut him up.=Bir şeyler söylemeye çalıştı, fakat başkan onu zınk diye susturdu.
The twenty rooms of the mansion were swept every day.=Konağın yirmi odası her gün süpürülürdü.
I think her tongue tripped.=Sanırım, sürçü lisan etti.
My tongue tripped.=Dilim sürçtü.
A mistake at the start of the day will go on all the way.=Sabah sürçen, geceye dek sürçer.
We would like to maintain our friendship to keep up.=Dostluğumuzu sürdürmek isteriz.
You can't pursue these activities here.=Bu faaliyetleri burada sürdüremezsiniz.
He'll pursue his study of law over there.=Orada hukuk öğrenimini sürdürecek.
We shall continue the fight at any cost.=Ne olursa olsun, bu savaşı sürdüreceğiz.
You shouldn't carry on that relationship any longer.=Bu ilişkiyi artık sürdürmemelisin.
How long will you be able to sustain that strike?=Bu grevi daha ne kadar sürdürebilirsiniz?
They were leading a very modest life.=Çok mütevâzi bir hayat sürdürüyorlardı.
Try to keep in touch with us.=Bizimle teması sürdürmeye çalışın.
This custom has been going on for years.=Bu adet yıllarca süregelmiştir.
No one shall be subjected to arbitrary exile.=Kimse keyfi olarak sürgün edilemez.
How long will this state of affairs continue?=Bu durum ne zamana kadar sürecektir?
I don't think this situation would continue for long.=Bu durumun uzun süreceğini sanmıyorum.
The bloody fighting went on all day long.=Kanlı savaş bütün gün sürdü.
Is this thing going on or not?=Bu iş sürüyor mu, sürmüyor mu?
They are happily married.=Evlilikleri mutlu bir şekilde sürüyor.
We dabbed her nose with some powder.=Burnuna biraz pudra sürdük.
Spread the jam very thin.=Reçeli çok ince sürünüz.
He spreads a huge layer of butter on his bread.=Ekmeğine kalın bir kat tereyağı sürer.
Don't expect any help from someone who needs it himself.=Kelin melhemi olsa, kendi başına sürer.
He was caught trying to pass off forged dollars.=Sahte dolar sürmeye çalışırken yakalandı.
It will take him a long time to get accustomed to his new job.=Yeni işine alışması uzun sürecektir.
It will take two weeks to repair it.=Tamir edilmesi iki hafta sürer.
How long does it generally take?=Genellikle ne kadar sürer?
It didn't take long.=Çok uzun sürmedi.
It shouldn't take more than ten minutes.=Bu iş, on dakikadan fazla sürmemelidir.
How long will it take to get there?=Oraya gitmek ne kadar sürer?
It won't take much longer now.=Artık, daha çok fazla sürmez.
Apparently the film lasts three hours and a half.=Film üç buçuk saat sürüyormuş.
It's too good to last.=Bu mutlu günler pek sürmez.
It won't last long.=Çok sürmez.
How long will the dinner last?=Yemek ne kadar sürecek?
New decrees are quickly ignored=Padişah yasağı üç gün sürer.
He did not touch his breakfast this morning.=Bu sabah kahvaltıyı ağzına sürmedi.
The minister's declaration has played into the hands of the opposition=Bakanın sözleri muhalefetin ekmeğine yağ sürmüştür.
He hasn't touched any food today.=Bugün yemeğe elini sürmedi.
Don't ask help from those who need it themselves.=Kelin ilacı olsa, başına sürer.
Apply a little at a time.=Azar azar sürünüz.
She still maintains that she's innocent.=Hâlâ suçsuz olduğunu ileri sürüyor.
I'm not trying to suggest anything.=Hiçbir şeyi ileri sürmeye çalışmıyorum.
They claim they have been cheated.=Aldatıldıklarını ileri sürüyorlar.
Why put forward excuses that no one will accept?=Kimsenin kabul etmeyeceği mazeretleri neden ileri sürelim.
Self defence can't be invoked in this case.=Bu durumda nefsi müdafaa ileri sürülemez.
Everyone is working and you're enjoying=Herkes çalışıyor, sen burada keyf sürüyorsun
She can't give any excuse for the conduct.=Bu davranış için hiçbir mazeret ileri süremez.
They put forward a few solutions=Birkaç çözüm öne sürdüler.
To keep bringing up the same topic time and time again.=Temcit pilavı gibi ısıtıp ısıtıp öne sürmek.
We are leading a very easy life here.=Burada çok rahat bir hayat sürüyoruz.
Why should others reap what I have sown?=Ben çekeyim cefayı, eller sürsün sefayı.
He was trying to pass off forged money.=Sahte para sürmeye çalışıyordu.
Sultan Suleiman the Magnificent reigned for long years.=Kanunî Sultan Süleyman uzun yıllar saltanat sürdü.
I see=Anlıyorum
I quit!=İstifa ediyorum, bırakıyorum, vazgeçiyorum.
Let's go!=Gidelim
Me too=Ben de
No way!=Olamaz!, Hiçbir şekilde
Come on=hadi
Hold on=Bekle
I agree=Aynı fikirdeyim
Not bad=Kötü değil
Not yet=Henüz değil
See you=Görüşürüz
Shut up!=Kapa çeneni
Why not?=Neden olmasın
Allow me=Bana izin ver
Be quiet!=Sessiz ol
Good job!=İyi iş
Have fun!=İyi eğlenceler
How much?=Ne kadar
I'm full=Tokum.
I'm home=Evdeyim
I'm lost=Kayboldum.
This way=Buradan, bu şekilde
After you=Senden sonra
God bless you!=Çok yaşa!
Follow me=Beni takip et
Forget it!=Unut onu, unut gitsin
Good luck!=İyi şanslar
I decline!=Reddediyorum
I promise=Söz veririm
Of course!=Tabiî ki
Slow down!=Yavaşla
Take care!=Kendine iyi bak, dikkat et
Try again=Tekrar dene
Watch out!=Dikkat et!
What's up?=Ne haber?
Be careful!=Dikkatli ol!
Don't move!=Kımıldama!
Guess what?=Tahmin et ne oldu?
I doubt it=Ondan şüpheliyim, Ondan şüphe ederim.
I think so=Sanırım öyle
Keep it up!=Aynen devam et!
Let me see=Bir bakayım
He looks very healthy=O çok sağlıklı gözüküyor
How much does it cost?=O ne kadar tutuyor, maliyeti nedir?
I'm very proud of you=Seninle gurur duyuyorum
It doesn't make sense=Bunun bir anlamı yok
None of your business!=Seni ilgilendirmez
What a nice day!=Ne güzel bir gün!
What's wrong with you?=Neyin var?
You are a chicken=Sen bir ödleksin
A lovely day, isn't it?=Hoş bir gün, değil mi?
He was born in New York.=O New York'ta doğdu.
It sounds great!=Kulağa harika geliyor!
It's a fine day=Güzel bir gün
What time is it?=Saat kaç?
You can make it!=Yapabilirsin
Control yourself!=Kendini kontrol et
He is ill=O hasta
How's everything?=Her şey nasıl?
I have no choice=Seçeneğim yok
I like ice cream=Dondurmayı severim
I love this game=Bu oyuna bayılırım
I'll try my best=Elimden gelenin en iyisini yapmaya çalışacağım
I'm on your side=Ben senin tarafındayım
Long time no see!=Uzun zamandır görüşmedik
No pain no gain=Acı yoksa kazanmakta yok
What a good deal!=Ne iyi bir anlaşma
What should I do?=Ne yapmalıyım
You asked for it!=Sen kaşındın
You have my word=Söz veriyorum.
Believe it or not!=İnan veya inanma
Don't count on me=Beni hesaba katma.
Never mind=Boş ver, zararı yok
No problem!=Sorun yok!
That's all!=Hepsi bu.
Time is up=Zaman doldu.
What's new?=Ne var ne yok?
Count me on=Ben varım, beni de sayın.
Don't worry=Endişelenme
I feel better=Daha iyi hissediyorum.
I love you!=Seni seviyorum.
I'm his fan=Onun hayranıyım
Is it yours?=Bu senin mi?
That's interesting=Bu ilginç.
Are you sure?=Emin misin?
Do l have to?=Yapmak zorunda mıyım?
No one knows=Kimse bilemez
What a pity!=Ne yazık!
Anything else?=Başka bir şey var mı?
Do me a favor=Bana bir iyilik yap
Help yourself=Kendine yardım et
I'm on a diet=Diyetteyim
Keep in touch=İrtibatı kesme.
Time is money=Vakit nakittir.
Who's calling?=Kim arıyor?
You did right=Doğru yaptın
Can I help you?=Yardım edebilir miyim?
Enjoy yourself!=Eğlenmene bak!
Excuse me.=Affedersiniz.
Give me a hand!=Bana yardımcı ol.
How's it going?=Nasıl gidiyor? Ne var ne yok?
I have no idea=Hiçbir fikrim yok
I just made it!=Şimdi yaptım.
I'm in a hurry!=Acelem var!
It's her field=Bu onun alanı.
It's up to you=Bu sana bağlı.
Wonderful!=Harika!
You're welcome=Bir şey değil.
Congratulations!=Tebrikler!
I can't help it=Benim elimde olan bir şey değil.
I didn't mean it=Onu demek istemedim.
I will be more careful=Çok daha dikkatli olacağım.
I will never forget it=Onu hiçbir zaman unutmayacağım
It rather surprised me=Bu beni oldukça şaşırttı.
Just around the corner=Eli kulağında.
Skating is interesting=Patenle kaymak ilgi çekicidir
That's a terrific idea!=Bu müthiş bir fikir.
What horrible weather!=Ne korkunç hava
Which would you prefer?=Hangisini tercih edersiniz?
He has a sense of humor=O şakadan anlar
He is acting an old man=O yaşlı bir adammış gibi hareket ediyor.
He is looking for a job=O iş arıyor.
He doesn't care about me=O beni umursamıyor.
I felt no regret for it=Onun için pişmanlık duymadım
I get up at six o'clock=Saat 6 da kalkarım.
I'm fed up with my work!=İşimden usandım.
It's no use complaining=Şikâyet etmenin bir anlamı yok.
Winter is a cold season=Kış soğuk bir mevsimdir.
You can call me any time=Beni istediğin zaman arayabilirsin.
All for one, one for all=Hepimiz birimiz birimiz hepimiz için.
East, west, home is best=Ne doğu ne batı evim en iyisi.
I am so sorry about this=Bunun için çok üzgünüm.
I can't afford a new car=Yeni bir araba almaya gücüm yetmiyor.
I want to see him now=Onu şimdi görmek istiyorum.
I have the right to know=Bilmeye hakkım var.
I'm not sure I can do it=Onu yapabileceğime emin değilim.
I'm not used to drinking=İçmeye alışkın değilim.
Let's not waste our time=Zamanımızı boşa harcamayalım.
May I ask some questions?=Sana birkaç soru sorabilir miyim?
Money is not everything=Para her şey değildir.
Stop making such a noise=Gürültü yapmayı kes.
That makes no difference=Bu fark yapmaz.
The price is reasonable=Bu fiyat uygundur.
What shall we do tonight?=Bu akşam ne yapalım?
What's your goal in life?=Hayattaki amacın ne?
Would you like some help?=Biraz yardım ister misin?
You're really killing me!=Beni gerçekten öldürüyorsun!
You've got a point there=İyi bir noktaya değindin.
Don't let me down=Beni hayal kırıklığına uğratma.
Easy come easy go=Kolay gelen kolay gider, Haydan gelen Huy'a gider
I beg your pardon=Affınıza sığınıyorum.
I'll be back soon=Çok yakın zamanda geri geleceğim
It's a long story=Uzun hikâye
Just wait and see!=Sadece bekle ve gör
Make up your mind=Kararını ver
That's all I need=İhtiyacım olan şey bu
The view is great=Manzara harika
The wall has ears=Yerin kulağı vardır.
What day is today?=Bugün günlerden ne?
What do you think?=Ne düşünüyorsun
Who told you that=Kim dedi sana bunu?
Yes, I suppose so=Evet galiba öyle
He is just a child=O sadece bir çocuk
I felt sort of ill=Kendimi hasta gibi hissettim
I have a good idea!=İyi bir fikrim var
It seems all right=Tamam gibi gözüküyor
May I use your pen?=Kaleminizi kullanabilir miyim?
That's a good idea=Bu iyi bir fikir
The answer is zero=Cevap sıfırdır
As soon as possible!=Mümkün olan en kısa sürede
If only I could fly=Keşke uçabilseydim
Accept my request=İsteğimi kabul et
All I can think about is you=Tek düşünebildiğim sensin
All I need is time=Tek istediğim zaman
I don't know what to do=Ne yaptığını bilmiyorum
no one understands you=Hiçkimse seni anlamıyor
Another interests?=Başka ilgi alanın?
Another time=Başka zaman
Anybody can do this.=Bunu kim olsa yapabilir.
Anything can happen.=Her şey olabilir.
Anytime you want=Ne zaman istersen
can we be a friend?=Arkadaş olalım mı?
Are you all right?=İyi misin?
Are you alone?=Yalnız mısın?
Are you blind?=Körmüsün
Are you busy=Meşgulmüsün
Are you deaf=Sağırmısın
Are you fond of swimming?=Yüzmekten hoşlanır mısınız?
Are you free tomorrow?=Yarın boş musun?
Are you ready?=Hazır mısın?
Are you single?=Bekar mısın?
Are you sleeping?=Yatıyor musun?
Are you there=Orda mısın?
Are you willing to try=Denemek istiyor musun?
Bad news travels fast=Kötü haber tez yayılır
Barking dog never bites=Havlayan köpek ısırmaz
Because of you=Senin yüzünden
Better late than never=Geç olsun da güç olmasın
Better lose the saddle than the horse=Zararın neresinden dönülürse kardır
Bye for a while=Bir süreliğine güle güle
Can I go?=Gidebilir miyim?
Can I show you something?=Size birşey gösterebilir miyim?
Can I take the other one?=Diğerini alabilir miyim?
Can you give me some water?=Bana biraz su verirmisin?
Can you help me?=Yardım edebilir misiniz?
Can you play the piano?=Piyano çalabilir misin?
Can you send me your picture?=Resmini gönderir misin?
Do you like me?=Benden hoşlanıyor musunuz?
Do you love me?=Beni seviyor musun?
Do you recognize me?=Beni tanıdın mı?
Do you remember me=Beni hatırladın mı?
Do you see any clouds?=Hiç bulut görüyor musun?
Do you speak english?=İngilizce biliyor musunuz?
Do you still have doubts that=Hala şüphelerin var mı
Do you understand my words?=Sözlerimi anlıyor musunuz?
Do you want a cup of coffee?=Bir fincan kahve ister misin?
Don't be late=Geç kalma
Don't believe what you hear=Duyduklarına inanma
Don't believe what you see=Gördüklerine inanma
Dont bother me=Benim canımı sıkma
Dont cry=Ağlama
Dont forget me=Beni unutma
Don't forget to call=Aramayı unutma
Don't lie to me=Yalan söleme bana
Don't look at me=Bana bakma
Don't make me wait=Beni bekletme
Enjoy your meal=Afiyet olsun
Even the best man sometimes stumbles=Hatasız kul olmaz
Every word I say is true=Her söylediğim kelime doğru
EverybOdy are standing under a big tree.=Herkes bir büyük ağacın altında duruyor.
Everyday together always=Her gün birlikteydik, her zaman
Excuse me.=Afedersiniz.
Fair enough.=Bu kadar yeter.
First you=Önce sen
Galatasaray is my favorite Football club.=Galatasaray benim favori takımımdır
Game is over=Oyun bitti
Get out=Çık dışarı
Give me your address=Adresini ver
God bless you=Çok yaşa
Good day=İyi günler
Good evening!=İyi akşamlar
Good night!=İyi geceler
Goodbye=Allahaısmarladık
Great=Harika
He can speak good English.=İngilizce'yi iyi konuşur.
He looks quit tired.=O oldukça yorgun görünüyor.
He never smokes.=O asla sigara içmez.
How are you?=Nasılsınız?
How could you do it!=Bunu nasıl yapabildin!
How much does it cost?=Fiyatı ne kadar?
How much is a kilo?=Kilosu kaçadır?
How much is it?=Kaç lira?
How old are you?=Kaç yaşındasınız?
I am in a hurry=Acelem var
I am interested in your past.=Senin geçmişinle ilgiliyim.
I am looking forward to seeing you.=Sizi görmek için sabırsızlanıyorum.
I am not as happy as you are.=Ben senin kadar mutlu değilim.
I am sure.=Eminim
I am surprised.=Şaşırdım.
I am tired.=Yorgunum.
I am very good at tennis.=Teniste iyiyimdir.
I am very happy.=Ben çok mutluyum.
I am well.=İyiyim.
I am very surprised.=Çok şaşırdım.
I can hardly hear you.=Seni zor duyuyorum.
I cant believe my ears.=Kulaklarıma inanamıyorum.
I can't hear you.=Sizi duyamıyorum.
I cant live without you.=Sensiz yaşayamam
I can't see anything=Hiçbir şey göremiyorum
I can't think=Düşünemiyorum
I didn't know.=Bilmiyordum.
I don`t know=Bilmiyorum
It sounds so good=Kulağa çok hoş geliyor
It`s time to go=Gitme zamanı geldi
It's so boring=Çok sıkıcı
Just tell me the truth=Bana sadece doğruyu söyle
Let me go=Bırak da gideyim
Let me introduce you myself=Sana kendimi tanıtıyım
Lets talk=Hadi konuşalım
Let's write=Yazişalım
Listen to me now=Şimdi beni dinle
Look into my eyes=Gözlerimin içine bak
May I help you?=Yardımcı olabilir miyim?
May I join you?=Size katılabilir miyim?
May I see your passport please?=Pasaport lütfen
Nevermind=Boşver
Once upon a time=Bir zamanlar
One more time=Bir kez daha
See you later!=Tekrar görüşmek üzere!
Shall we start now?=Artık başlayalım mı?
Shit=Kahretsin
So so=Eh, şöyle böyle
Somebody is calling you.=Birisi seni arıyor.
Take a rest=Biraz dinlen
Take care=Kendine iyi bak
Take it easy=Keyfine bak, kolay gelsin
Take me home.=Beni eve götür.
Thanks, but thanks.=Teşekkürler, ama yine de sağol.
I would like to pay for this=Ben ödemek istiyorum
I would rather drink coffee than tea.=Çay yerine kahve içmeyi yeğlerim.
If I could I would turn back the time=Elimde olsa zamanı geri alırdım
I'll find you wherever you go.=Nereye gidersen git seni bulacağım.
It does not matter=Önemli değil
It doesnt make any difference=Fark etmez
It is on the tip of my tongue=Dilimin ucunda
It's the most boring film I've ever seen.=Hayatımda gördüğüm en sıkıcı film.
I need you=Sana ihtiyacım var
I will be right back=Hemen döneceğim
It is broken=Bu bozuk.
The choice is yours=Seçim senin
The exam is on Monday.=Sınav pazartesi günüdür.
There's no hope=Hiç umut yok
There's no need to argue=Tartışmaya gerek yok
Wait a minute=Bir saniye bekle
Wait a moment=Biraz bekle
What a pity!=Ne yazık!
What a shame!=Ne ayıp!
What are you doing tonight?=Bu akşam ne yapıyorsun?
What are you doing?=Ne yapıyorsun?
What are you looking for ?=Siz ne arıyorsunuz?
What are you talking about?=Ne konuşuyorsunuz?
What are your hobbies?=Hobilerin nelerdir?
What can I do for you?=Sizin için ne yapabilirim?
What do you do in your spare times?=Boş zamanlarında ne yapıyorsun?
Hi! My name is Yousuf=Merhaba! Benim ismim Yusuf.
Where are you from=Nerelisin?
I'm from Turkey=Türkiye'den geliyorum.
How old are you?=Kaç yaşındasın?
How are you=Nasılsın?
What's up=Nasıl gidiyor?
Couldn't be better=Daha iyisi olamazdı.
I'm fine. Thank you for asking.=Ben iyiyim. Sorduğun için teşekkür ederim.
Good morning=Günaydın.
Good night=İyi geceler.
How is your family=Ailen nasıl?
How about you=Senden naber?
Nice yo meet you=Tanıştığımıza sevindim.
That my pleasure=O zevk bana ait.
Are you okay=İyi misiniz?
No, i'm not okay=Hayır, iyi değilim.
Where can i find the police?=Polisi nerede bulabilirm?
Excuseme=Affedersiniz.
Can you help me, please?=Lütfen yardım eder misiniz?
This is very kind of you=Çok naziksiniz.
Good to see you=Seni gördüğüme sevindim.
Take care yourself=Kendine iyi bak
See you later=Sonra görüşürüz.
I'll miss you=Seni özleyeceğim
Bye bye=Güle güle
How can I get to the museum=Müzeye nasıl gidebilirim
Where am I?=Nerdeyim?
I'm little bit a nerveous=Biraz gerginim.
Calm down=Sakin ol.
Relax=Rahatla.
I'm not feeling good=İyi hissetmiyorum.
Congratulations=Tebrikler.
Good job=İyi iş.
You did it=Başardın.
Cheers=Şerefe.
I'm proud of you=Seninle gurur duyuyorum.
You are welcome=Rica ederim.
I'm flattered=Gururum okşandı.
Let's do this=Hadi yapalım!
Let's go=Hadi gidelim!
Give me five=Çak bir beşlik!
What a night=Ne gece ama.
You can make it=Yapabilirsin!
Will you marry me?=Benimle evlenir misin?
Will you go out with me?=Benimle çıkar mısın?
Do you wanna hang out?=Takılmak ister misin?
Shut up!=Kapa çeneni!
Oh my god!=Aman tanrım!
Thanks god!=Şükürler olsun!
Don't move=Sakın kımıldama!
Don't give up!=Asla pes etme!
Suprise!=Sürpriz!
None of your bussines!=Seni ilgilendirmez!
Do you have reservation?=Rezervasyon yaptırmış mıydınız?
May I see the menu?=Menüyü görebilir miyim?
I'd like to order=Şipariş vermek istiyorum.
Here you go=Buyrun.
Enjoy your meal=Afiyet olsun.
Keep the change=Üstü kalsın.
Is there anything I can get for you=Sizin için yapabilceğim bir şey var mı?
Thank you, I'm just koolking=Sağolun, sadece bakınıyorum
Do you now what size you are?=Bedeninizi biliyor musunuz?
I don't now my size=Bedenimi bilmiyorum.
I want to try this on=Bunu denemek istiyorum.
Where is the fitting room=Soyunma odası nerede?
How much is it?=Ne kadar?
Do you make payment?=Taksit yapıyor musunuz?
I want to pay by credit card=Kredi kartıyla ödemek istiyorum.
Can you gift wrapped?=Hediye paketi yapar mısınız?
That your fault=Bu senin hatan.
I'dont wanna see you anymore=Seni artık görmek istemiyorum.
I can't believe you=İnanamıyorum sana
How could you do this to me=Bunu bana nasıl yapabildin?
If you can dream it, you can do it=Hayal edebiliyorsan, yapabilirsin.
Give me a hand=Yardım et.
Let's face it=Hadi yüzleşelim.
That is piece of cake=Çantada keklik.
Better late than never=Geç olması hiç olmamasından iyidir.
Clear the air=Açıklığa kavuşturmak.
Freeze!=Olduğun yerde kal!
After you=Önden siz buyrun
Allow me=Bana izin ver
A lovely day, isn't it?=Hoş bir gün, değil mi?
Any thing else?=Başka bir şey var mı?
Any day will do=Herhangi bir gün bana uğra
Are you kidding?=Şaka mı yapıyorsun? Kafa mı buluyorsun?
Are you sure?=Emin misin?
As for me=Bence
As soon as possible=Mümkün olan en kısa sürede
Be careful!=Dikkatli ol!
Be calm!=Sakin ol!
Be patient!=Sabırlı ol!
Be quiet!=Sessiz ol
Bottoms up!=Şerefe! İçkiyi bir yudumda bitirmek. Fondip yapmak
Bless you!=Çok yasa!
By the way=Bu arada..
Can I help you?=Yardım edebilir miyim?
Can you repeat it?=Tekrar eder misin?
Cheer up!=Neşelen
Come on=Yapma, hadi ama
Congratulations!=Tebrikler!
Count me on, count me in=Ben varım, beni de sayın.
Do l have to?=Yapmak zorunda mıyım?
Do me a favor=Bana bir iyilik yap
Do you understand?=Anladın mı?
Don't be so childish=Çocuk olma, çocuk gibi davranma
Don't be ridiculous=Komik olma
Don't be so modest=Alçak gönüllü olma
Don't keep the truth from me=Benden gerçekleri saklama
Don't let me down=Beni hayal kırıklığına uğratma
Don't move!=Kımıldama!
Don't worry=Endişelenme
Enjoy yourself!=Eğlenmene bak!
Excuse me Sir=Affedersiniz efendim
Feel beter=Daha iyi hissetmek, daha iyi olmak
Follow me=Beni takip et
Forget it!=Unut onu, unut gitsin
Forgive me=Beni affet
For what?=Ne için?
Give me a hand!=Bana yardımcı ol.
Good job!=İyi iş
Good luck!=İyi şanslar
Have fun!=İyi eğlenceler veya eğlen
He can't take a joke=O şakadan anlamaz
He doesn't care about me=Beni umursamıyor
He has a large income=Onun kazancı çok, iyi para kazanıyor
He is saving money=Para biriktiriyor
He is my age=O benim yaşımda
He is just a child=O sadece bir çocuk
He is totally exhausted=O tamamen bitmişti, tükenmişti
He looks very healthy=O çok sağlıklı gözüküyor
He paused for a reply=Cevap vermek için durdu
He repaired his house=O onun evini tamir etti
He suggested a picnic=Piknik yapmayı önerdi
Help yourself=Kendine yardım et
Here's a gift for you=Bu senin için bir hediye, işte hediyen!
Hold on=Bekle
How are things going?=İşler nasıl gidiyor?
How do I look?=Nasıl görünüyorum?
How's it going?=Nasıl gidiyor? Ne var ne yok?
How much?=Ne kadar
How much does it cost?=O ne kadar tutuyor, maliyeti nedir?
I agree=Aynı fikirdeyim, sana katılıyorum
I caught the last bus=Son otobüse yetiştim
I can't help it=Benim elimde olan bir şey değil.
I could hardly speak=Zorlukla konuşabildim
I decline!=Reddediyorum
I don't mean it=Onu demek istemedim, onu kasdetmedim.
I dont understand=Anlamadım
I doubt it=Ondan şüpheliyim, Ondan şüphe ederim.
I have a suprise for you=Senin için bir sürprizim var
I have no idea=Hiçbir fikrim yok
I have something to tell you=Sana söyleyeceğim bir şey var
I have the right to know=Bilmeye hakkım var
I just made it!=Şimdi yaptım.
I know all about it=Bütün ayrıntılarıyla biliyorum
I know what I said=Ne dediğimi biliyorum
I love you!=Seni seviyorum.
I'll arange everything=Herşeyi ayarlayacağım
I'll back soon=Çok yakın zamanda geri döneceğim
I'll be more careful=Daha dikkatli olacağım
I'll be right there=Hemen geliyorum
I'll have to try that=Bunu denemek zorundayım
I'll fix you up=Sizinle ilgileneceğim
I'll see to it=O işi hallederim ben.
I'm afraid that I have to go=Korkarım gitmem gerekiyor
I'm busy=Meşgulüm, yoğunum
I'm full=Tokum.
I'm his fan=Onun hayranıyım
I'm home=Evdeyim
I'm in a hurry!=Acelem var
I'm lost=Kayboldum.
I'm not sure I can do it=Yapabilir miyim emin değilim
I'm on a diet=Diyetteyim
I'm single=Bekârım
I'm so sorry about this=Bunun için çok üzgünüm
I'm sorry=Özür dilerim, üzgünüm
I'm sure=Eminin
I'm sure of it=Ondan eminim
I'm very proud of you=Seninle gurur duyuyorum
I need to do this=Bunu yapmaya ihtiyacım var
I saw it with my own eyes=Kendi gözlerimle gördüm
I see=Anlıyorum
I quit!=İstifa ediyorum, bırakıyorum, vazgeçiyorum.
I promise=Söz veririm
I think so=Sanırım öyle
In that case=Bu durumda
Is it true or false?=Doğru mu yanlış mı?
Is it yours?=Bu senin mi?
It doesn't make sense=Bunun bir anlamı yok
It doesn't matter=Fark etmez
It really takes time=Bu gerçekten zaman alır
It's fort he best=Böylesi daha iyi
It's her field=En iyi o bilir, onun alanı
It's none of your business=Sizi ilgilendirmez
It's not a question of that=Mesele o değil
It's a good idea=BU iyi bir fikir
It's a long story=Uzun hikaye
It's just what I need=Bu tam da ihtiyacım olan şey
It's not a good idea=Bu iyi bir fikir değil
It's no use complaining=Şikayet etmenin anlamı yok
It's ok=Herşey tamam, herşey yolunda
It's on the tip of my tongue=Dilimin ucunda
It's too good to be ture=Gerçek olamayacak kadar iyi
It's up to you=Bu sana bağlı
It's very thoughtful of you=Çok düşüncelisin
It's your turn=Sen sıran
It seems all right=Tamam gibi gözüküyor
Just a minute=Sadece 1 dakika izin ver
Just wonderful!=Harika!
Keep in touch=Muhafaza et, irtibatı kesme, teması kesme
Keep it up!=Aynen devam et!
Keep your promise=Sözünü tut
Let me see=Bir bakayım
Let's go!=Hadi gidelim!
Let's not waste our time=Zamanımızı boşa harcamayalım
Make yourself at home=Kendini evdeymiş gibi hisset
Me too=Ben de
Mind your own business=Siz kendi işinize bakın!
More or less=Aşağı yukarı
Move out of my way!=Yolumdan çekil!
My car needs washing=Arabamın yıkamaya ihtiyacı var
My god!=Aman Tanrım
My treat=Bu benden.
Neither you nor he is wrong=Ne sen hatalısın ne de o
Never mind=Boş ver, zararı yok
None of your business!=Seni ilgilendirmez
No one knows=Kimse bilemez
No problem!=Sorun yok
No way!=Olamaz! Hiçbir şekilde, hiçbir yol,
Not a sound was heard=Sessizlik hâkimdi, çıt yoktu
Not bad=Kötü değil, fena değil
Not yet=Henüz değil
Of course!=Tabiî ki
See you=Görüşürüz Shut up!: Kapa çeneni
Slow down!=Yavaşla
So do I=Bence de
So it seems=Öyle görünüyor
So long=Hoşça kal, oldukça uzun
So much the beter=Daha iyi ya, Tam isabet!
So so=şöyle böyle, eh işte
Stop making such a noise=Gürültü yapmayı kes
Take care!=Kendine iyi bak, dikkat et
Take it easy=Rahatına bak, kafana takma, boşver
Tell the truth=Doğruyu söyle
Thank you=Teşekkür ederim
Thank you for your advice=Önerin için teşekkür ederim
Thank you for your effort=Çabanız için teşekkür ederim.
That's always the case=Her zaman öyledir.
That's all!=Hepsi bu, bu kadar.
That's all for now=Şimdilik bu kadar
That's neat=İlginç bir şey
That's the worst of it!=Bu olabileceğin en kötüsüdür.
The road divides here=Yol burada ayrılıyor
The whole world knows that=Bütün dünya bunu bilir
They hurt=Onlar acıtır, bu incitir
Things are getting beter=İşler iyiye gidiyor
Time after time=Zaman zaman
Time is money=Zaman paradır
Time is running out=Zaman tükeniyor
This way=Buradan ya da bu şekilde
Time is up=Zaman doldu, süre bitti.
To be careful!=Dikkatli olmak
Try again=Tekrar dene
Watch out!=Dikkat et!
What about you?=Sen bu konuda ne düşünüyorsun?
What a nice day!=Ne güzel bir gün!
What a pity!=Ne yazık!
What does it mean?=Bu ne anlama geliyor?
What do you think?=Ne düşünüyorsun?
What happened?=Ne oldu?
What happened to you?=Sana ne oldu?
What's new?=Ne haber
What's the matter?=Ne var, ne oldu?
What's up?=Ne haber?
What's wrong with you?=Neyin var?
What's your trouble?=Senin derdin ne?
Who's calling?=Kim arıyor, kim çağırıyor
Who tall you that?=Bunu sana kim dedi?
Would you like some help?=Yardım ister misin?
Why not?=Neden olmasın
Yes, I suppose so=Evet, galiba öyle
You are a chicken=Sen bir ödleksin
You are just in time=Tam zamanında geldin
You are really killing me=Beni gerçekten öldürüyorsun
You can get what you want=Ne istersen alabilirsin
You did right=Doğru yaptın
You have got a point there=İyi bir noktaya değindin
You here that?=Duydun mu?
You owe me one=Bana borçlusun
You're welcome=Birşey değil
You set me up!=Bana tezgâh kurdun!